services:
  pg_db:
    container_name: postgresdb
    image: postgres:16.2-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: "${PG_DBNAME}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: ./.env
  
volumes:
  postgres_data:


